#include "vme_ibf/serialization.hpp"
#include "vme_ibf/group_utils.hpp"
#include "internal/crypto.hpp"
#include <algorithm>
#include <cstring>
#include <limits>
#include <stdexcept>

namespace vme_ibf { namespace {
constexpr std::uint16_t VER=2,CURVE=1; constexpr std::size_t HDR=16;
bool addok(size_t a,size_t b,size_t&z){if(a>std::numeric_limits<size_t>::max()-b)return false;z=a+b;return true;}bool mulok(size_t a,size_t b,size_t&z){if(a&&b>std::numeric_limits<size_t>::max()/a)return false;z=a*b;return true;}
bool dim(size_t d,size_t&n){if(d<1||d>kMaxSerializedDimension||d>=std::numeric_limits<size_t>::digits)return false;n=size_t{1}<<d;return true;}
void err(DecodeError*p,DecodeError e){if(p)*p=e;}
void raw(Bytes&o,std::span<const uint8_t>x){o.insert(o.end(),x.begin(),x.end());}
void header(Bytes&o,const char*m,size_t d){o.insert(o.end(),m,m+8);append_u16_be(o,VER);append_u16_be(o,CURVE);append_u32_be(o,static_cast<uint32_t>(d));}
uint16_t u16(std::span<const uint8_t>b,size_t p){return uint16_t(uint16_t(b[p])<<8|b[p+1]);}uint32_t u32(std::span<const uint8_t>b,size_t p){return(uint32_t(b[p])<<24)|(uint32_t(b[p+1])<<16)|(uint32_t(b[p+2])<<8)|b[p+3];}
bool head(std::span<const uint8_t>b,const char*m,size_t&d,DecodeError*e){if(b.size()<HDR){err(e,DecodeError::Truncated);return false;}if(!std::equal(b.begin(),b.begin()+8,reinterpret_cast<const uint8_t*>(m))){err(e,DecodeError::WrongMagic);return false;}if(u16(b,8)!=VER){err(e,DecodeError::UnsupportedVersion);return false;}if(u16(b,10)!=CURVE){err(e,DecodeError::WrongCurve);return false;}d=u32(b,12);size_t n;if(!dim(d,n)){err(e,DecodeError::InvalidDimension);return false;}return true;}
bool length(std::span<const uint8_t>b,size_t n,DecodeError*e){if(b.size()<n){err(e,DecodeError::Truncated);return false;}if(b.size()>n){err(e,DecodeError::TrailingBytes);return false;}return true;}
template<class T>bool dec(std::span<const uint8_t>b,T&o,size_t want,bool valid){if(b.size()!=want)return false;T x;size_t n=x.deserialize(b.data(),b.size());if(n!=b.size())return false;if(!valid)return false;if(serialize(x)!=Bytes(b.begin(),b.end()))return false;o=x;return true;}
template<class T>bool take(std::span<const uint8_t>b,size_t&p,size_t n,T&o,bool(*fn)(std::span<const uint8_t>,T&)){if(p>b.size()||n>b.size()-p)return false;T decoded;if(!fn(b.subspan(p,n),decoded))return false;p+=n;o=std::move(decoded);return true;}
Digest statement_digest(const VmeIbfCRS&c,const Digest&id,const G2&X){Bytes b;append_frame(b,"VME.BF.G2/STATEMENT/V2");append_frame(b,c.digest);append_frame(b,id);append_frame(b,serialize(X));return sha256(b);}
bool pre_shape(size_t d,const VmeIbfPrecomputation&p){return p.pairing_x.size()==d+1&&p.delta1R.size()==d&&p.delta2R.size()==d;}
bool proof_elements(const VmeIbfProof&p){if(!valid_g1(p.R)||!valid_g1(p.PhiFinal)||!valid_g2(p.ThetaFinal))return false;for(const auto&r:p.rexp_claims)for(const GT*x:{&r.E,&r.F,&r.TL,&r.TR})if(!internal::valid_gt(*x))return false;for(const auto&f:p.dory_folds)for(const GT*x:{&f.D1L,&f.D1R,&f.D2L,&f.D2R,&f.W1,&f.W2})if(!internal::valid_gt(*x))return false;for(const auto&u:p.batch_U)if(!internal::valid_gt(u))return false;return true;}
}
void append_u16_be(Bytes&o,uint16_t x){o.push_back(uint8_t(x>>8));o.push_back(uint8_t(x));}void append_u32_be(Bytes&o,uint32_t x){for(int s=24;s>=0;s-=8)o.push_back(uint8_t(x>>s));}void append_u64_be(Bytes&o,uint64_t x){for(int s=56;s>=0;s-=8)o.push_back(uint8_t(x>>s));}
Bytes serialize_fr(const Fr&x){return serialize(x);}Bytes serialize_g1(const G1&x){return serialize(x);}Bytes serialize_g2(const G2&x){return serialize(x);}Bytes serialize_gt(const GT&x){return serialize(x);}
CanonicalElementSizes canonical_element_sizes(){initialize();Fr f;f=1;G1 p;mcl::bn::hashAndMapToG1(p,"size-g1",7);G2 q;mcl::bn::hashAndMapToG2(q,"size-g2",7);GT t;mcl::bn::pairing(t,p,q);return{serialize(f).size(),serialize(p).size(),serialize(q).size(),serialize(t).size()};}
bool deserialize_fr(std::span<const uint8_t>b,Fr&o){auto s=canonical_element_sizes();Fr x;if(b.size()!=s.fr_bytes||x.deserialize(b.data(),b.size())!=b.size()||serialize(x)!=Bytes(b.begin(),b.end()))return false;o=x;return true;}
bool deserialize_g1(std::span<const uint8_t>b,G1&o){auto s=canonical_element_sizes();G1 x;if(b.size()!=s.g1_bytes||x.deserialize(b.data(),b.size())!=b.size()||!valid_g1(x)||serialize(x)!=Bytes(b.begin(),b.end()))return false;o=x;return true;}
bool deserialize_g2(std::span<const uint8_t>b,G2&o){auto s=canonical_element_sizes();G2 x;if(b.size()!=s.g2_bytes||x.deserialize(b.data(),b.size())!=b.size()||!valid_g2(x)||serialize(x)!=Bytes(b.begin(),b.end()))return false;o=x;return true;}
bool deserialize_gt(std::span<const uint8_t>b,GT&o){auto s=canonical_element_sizes();GT x;if(b.size()!=s.gt_bytes||x.deserialize(b.data(),b.size())!=b.size()||!internal::valid_gt(x)||serialize(x)!=Bytes(b.begin(),b.end()))return false;o=x;return true;}
std::size_t proof_mathematical_payload_bytes(size_t d,const CanonicalElementSizes&s){size_t n;if(!dim(d,n))throw std::invalid_argument("invalid d");size_t a,b,z;if(!mulok(11*d-4,s.gt_bytes,a)||!mulok(2,s.g1_bytes,b)||!addok(a,b,z)||!addok(z,s.g2_bytes,z))throw std::overflow_error("size");return z;}std::size_t proof_wire_bytes(size_t d,const CanonicalElementSizes&s){size_t z=proof_mathematical_payload_bytes(d,s);if(!addok(z,HDR,z))throw std::overflow_error("size");return z;}
std::size_t crs_wire_bytes(size_t d,const CanonicalElementSizes&s){size_t n;if(!dim(d,n))throw std::invalid_argument("invalid d");size_t a,b,z;if(!mulok(n+1,s.g1_bytes,a)||!mulok(n+1,s.g2_bytes,b)||!addok(HDR,a,z)||!addok(z,b,z))throw std::overflow_error("size");return z;}std::size_t precomputation_wire_bytes(size_t d,const CanonicalElementSizes&s){size_t n;if(!dim(d,n))throw std::invalid_argument("invalid d");size_t a,z;if(!mulok(3*d+2,s.gt_bytes,a)||!addok(HDR+32,a,z))throw std::overflow_error("size");return z;}std::size_t statement_wire_bytes(size_t d,const CanonicalElementSizes&s){size_t n;if(!dim(d,n))throw std::invalid_argument("invalid d");size_t a,z;if(!mulok(n,s.fr_bytes,a)||!addok(HDR+32,a,z)||!addok(z,s.g2_bytes,z))throw std::overflow_error("size");return z;}
Bytes serialize_crs(const VmeIbfCRS&c){size_t n;if(!dim(c.d,n)||!validate_crs(c))throw std::invalid_argument("invalid CRS");Bytes o;header(o,"VIBFCRS2",c.d);for(auto&x:c.G)raw(o,serialize(x));for(auto&x:c.H)raw(o,serialize(x));raw(o,serialize(c.L));raw(o,serialize(c.Lprime));return o;}
bool deserialize_crs(std::span<const uint8_t>b,VmeIbfCRS&o,DecodeError*e){err(e,DecodeError::None);size_t d,n;if(!head(b,"VIBFCRS2",d,e)||!dim(d,n))return false;auto s=canonical_element_sizes();size_t expected;try{expected=crs_wire_bytes(d,s);}catch(...){err(e,DecodeError::SizeOverflow);return false;}if(!length(b,expected,e))return false;VmeIbfCRS x;x.d=d;x.n=n;x.G.resize(n);x.H.resize(n);size_t p=HDR;for(auto&q:x.G){if(!take(b,p,s.g1_bytes,q,deserialize_g1)||q.isZero()){err(e,q.isZero()?DecodeError::IdentityNotAllowed:DecodeError::InvalidG1);return false;}}for(auto&q:x.H){if(!take(b,p,s.g2_bytes,q,deserialize_g2)||q.isZero()){err(e,q.isZero()?DecodeError::IdentityNotAllowed:DecodeError::InvalidG2);return false;}}if(!take(b,p,s.g1_bytes,x.L,deserialize_g1)||x.L.isZero()){err(e,x.L.isZero()?DecodeError::IdentityNotAllowed:DecodeError::InvalidG1);return false;}if(!take(b,p,s.g2_bytes,x.Lprime,deserialize_g2)||x.Lprime.isZero()){err(e,x.Lprime.isZero()?DecodeError::IdentityNotAllowed:DecodeError::InvalidG2);return false;}x.digest=compute_crs_digest(x);o=std::move(x);return true;}
Bytes serialize_precomputation(const VmeIbfCRS&c,const VmeIbfPrecomputation&p){if(!validate_crs(c)||!validate_precomputation_shape(c,p)||!validate_precomputation_elements(p))throw std::invalid_argument("invalid precomputation");Bytes o;header(o,"VIBFPRE2",c.d);raw(o,c.digest);for(auto&x:p.pairing_x)raw(o,serialize(x));for(auto&x:p.delta1R)raw(o,serialize(x));for(auto&x:p.delta2R)raw(o,serialize(x));raw(o,serialize(p.pairing_LLprime));return o;}
bool deserialize_precomputation(std::span<const uint8_t>b,const VmeIbfCRS&c,VmeIbfPrecomputation&o,DecodeError*e){err(e,DecodeError::None);if(!validate_crs(c)){err(e,DecodeError::InvalidCrs);return false;}size_t d;if(!head(b,"VIBFPRE2",d,e))return false;if(d!=c.d){err(e,DecodeError::InvalidDimension);return false;}auto s=canonical_element_sizes();size_t expected;try{expected=precomputation_wire_bytes(d,s);}catch(...){err(e,DecodeError::SizeOverflow);return false;}if(!length(b,expected,e))return false;size_t p=HDR;if(!std::equal(b.begin()+p,b.begin()+p+32,c.digest.begin())){err(e,DecodeError::CrsDigestMismatch);return false;}p+=32;VmeIbfPrecomputation x;x.pairing_x.resize(d+1);x.delta1R.resize(d);x.delta2R.resize(d);for(auto*vec:{&x.pairing_x,&x.delta1R,&x.delta2R})for(auto&q:*vec)if(!take(b,p,s.gt_bytes,q,deserialize_gt)){err(e,DecodeError::InvalidGT);return false;}if(!take(b,p,s.gt_bytes,x.pairing_LLprime,deserialize_gt)){err(e,DecodeError::InvalidGT);return false;}o=std::move(x);return true;}
bool validate_precomputation(const VmeIbfCRS&c,const VmeIbfPrecomputation&p){return audit_precomputation(c,p);}
Bytes serialize_statement(const VmeIbfCRS&c,const VmeIbfStatement&s){if(!validate_crs(c)||!validate_statement_shape(c,s)||!validate_statement_elements(s)||!validate_statement_digest(c,s))throw std::invalid_argument("invalid statement");Bytes o;header(o,"VIBFSTM2",c.d);raw(o,c.digest);for(auto&x:s.x)raw(o,serialize(x));raw(o,serialize(s.X));return o;}
bool deserialize_statement(std::span<const uint8_t>b,const VmeIbfCRS&c,VmeIbfStatement&o,DecodeError*e){err(e,DecodeError::None);if(!validate_crs(c)){err(e,DecodeError::InvalidCrs);return false;}size_t d;if(!head(b,"VIBFSTM2",d,e))return false;if(d!=c.d){err(e,DecodeError::InvalidDimension);return false;}auto s=canonical_element_sizes();size_t expected;try{expected=statement_wire_bytes(d,s);}catch(...){err(e,DecodeError::SizeOverflow);return false;}if(!length(b,expected,e))return false;size_t p=HDR;if(!std::equal(b.begin()+p,b.begin()+p+32,c.digest.begin())){err(e,DecodeError::CrsDigestMismatch);return false;}p+=32;VmeIbfStatement x;x.x.resize(c.n);for(auto&q:x.x)if(!take(b,p,s.fr_bytes,q,deserialize_fr)){err(e,DecodeError::InvalidFr);return false;}if(!take(b,p,s.g2_bytes,x.X,deserialize_g2)){err(e,DecodeError::InvalidG2);return false;}auto id=compute_statement_input_digest(c,x.x);x.digest=statement_digest(c,id,x.X);o=std::move(x);return true;}
Bytes serialize_proof(size_t d,const VmeIbfProof&p){size_t n;if(!dim(d,n)||p.rexp_claims.size()!=d-1||p.dory_folds.size()!=d||p.batch_U.size()!=d||!proof_elements(p))throw std::invalid_argument("invalid proof");Bytes o;header(o,"VIBFPRF2",d);for(auto&x:p.rexp_claims){raw(o,serialize(x.E));raw(o,serialize(x.F));raw(o,serialize(x.TL));raw(o,serialize(x.TR));}raw(o,serialize(p.R));for(size_t k=0;k<d;++k){auto&x=p.dory_folds[k];raw(o,serialize(x.D1L));raw(o,serialize(x.D1R));raw(o,serialize(x.D2L));raw(o,serialize(x.D2R));raw(o,serialize(x.W1));raw(o,serialize(x.W2));raw(o,serialize(p.batch_U[k]));}raw(o,serialize(p.PhiFinal));raw(o,serialize(p.ThetaFinal));return o;}
bool deserialize_proof(std::span<const uint8_t>b,const VmeIbfCRS&c,VmeIbfProof&o,DecodeError*e){err(e,DecodeError::None);if(!validate_crs(c)){err(e,DecodeError::InvalidCrs);return false;}size_t d;if(!head(b,"VIBFPRF2",d,e))return false;if(d!=c.d){err(e,DecodeError::InvalidDimension);return false;}auto s=canonical_element_sizes();size_t expected;try{expected=proof_wire_bytes(d,s);}catch(...){err(e,DecodeError::SizeOverflow);return false;}if(!length(b,expected,e))return false;size_t p=HDR;VmeIbfProof x;x.rexp_claims.resize(d-1);for(auto&q:x.rexp_claims)for(GT*z:{&q.E,&q.F,&q.TL,&q.TR})if(!take(b,p,s.gt_bytes,*z,deserialize_gt)){err(e,DecodeError::InvalidGT);return false;}if(!take(b,p,s.g1_bytes,x.R,deserialize_g1)){err(e,DecodeError::InvalidG1);return false;}x.dory_folds.resize(d);x.batch_U.resize(d);for(size_t k=0;k<d;++k){auto&q=x.dory_folds[k];for(GT*z:{&q.D1L,&q.D1R,&q.D2L,&q.D2R,&q.W1,&q.W2})if(!take(b,p,s.gt_bytes,*z,deserialize_gt)){err(e,DecodeError::InvalidGT);return false;}if(!take(b,p,s.gt_bytes,x.batch_U[k],deserialize_gt)){err(e,DecodeError::InvalidGT);return false;}}if(!take(b,p,s.g1_bytes,x.PhiFinal,deserialize_g1)){err(e,DecodeError::InvalidG1);return false;}if(!take(b,p,s.g2_bytes,x.ThetaFinal,deserialize_g2)){err(e,DecodeError::InvalidG2);return false;}o=std::move(x);return true;}
}
