#include "vme_ibf/symbolic_gt.hpp"
#include "vme_ibf/group_utils.hpp"
#include <chrono>
#include <map>
namespace vme_ibf { namespace {Fr onefr(){Fr x;x=1;return x;}template<class K>void add(std::map<K,Fr>&m,const K&id,const Fr&y){auto it=m.find(id);if(it==m.end()){Fr zero;zero.clear();it=m.emplace(id,zero).first;}Fr::add(it->second,it->second,y);}}
SymbolicGtExpression gt_atom(GtAtomId id){SymbolicGtExpression e;e.gt_terms[id]=onefr();return e;}SymbolicGtExpression pairing_atom(PairingAtomId id){SymbolicGtExpression e;e.pairing_terms[id]=onefr();return e;}
void multiply_in_place(SymbolicGtExpression&d,const SymbolicGtExpression&s){for(auto&[id,c]:s.gt_terms)add(d.gt_terms,id,c);for(auto&[id,c]:s.pairing_terms)add(d.pairing_terms,id,c);}SymbolicGtExpression multiplied(const SymbolicGtExpression&a,const SymbolicGtExpression&b){auto z=a;multiply_in_place(z,b);return z;}
void power_in_place(SymbolicGtExpression&e,const Fr&s){for(auto&[id,c]:e.gt_terms)Fr::mul(c,c,s);for(auto&[id,c]:e.pairing_terms)Fr::mul(c,c,s);}SymbolicGtExpression powered(const SymbolicGtExpression&e,const Fr&s){auto z=e;power_in_place(z,s);return z;}
void normalize(SymbolicGtExpression&e){for(auto i=e.gt_terms.begin();i!=e.gt_terms.end();)if(i->second.isZero())i=e.gt_terms.erase(i);else++i;for(auto i=e.pairing_terms.begin();i!=e.pairing_terms.end();)if(i->second.isZero())i=e.pairing_terms.erase(i);else++i;}
GT evaluate_pairing_terms_reference(const SymbolicGtExpression&e,const PairingAtomResolver&r,PairingProductStats*s){PairingProductStats z;GT out;out.setOne();for(auto&[id,c]:e.pairing_terms){if(c.isZero())continue;++z.input_pairing_terms;auto p=r(id);G1 scaled;G1::mul(scaled,p.first,c);if(scaled.isZero())continue;GT q;mcl::bn::pairing(q,scaled,p.second);GT::mul(out,out,q);++z.coalesced_pairing_terms;++z.miller_loop_batches;++z.miller_loop_terms;++z.final_exponentiations;++z.ordinary_pairing_calls;}if(s)*s=z;return out;}
GT evaluate_pairing_terms_multi(const SymbolicGtExpression&e,const PairingAtomResolver&r,PairingProductStats*s){PairingProductStats z;struct Acc{G1 p;G2 q;};std::map<Bytes,Acc>groups;for(auto&[id,c]:e.pairing_terms){if(c.isZero())continue;++z.input_pairing_terms;auto in=r(id);G1 scaled;G1::mul(scaled,in.first,c);if(scaled.isZero())continue;Bytes key=serialize(in.second);auto it=groups.find(key);if(it==groups.end()){Acc a;a.p=scaled;a.q=in.second;groups.emplace(std::move(key),a);}else G1::add(it->second.p,it->second.p,scaled);}std::vector<G1>p;std::vector<G2>q;p.reserve(groups.size());q.reserve(groups.size());for(auto&[key,a]:groups)if(!a.p.isZero()){p.push_back(a.p);q.push_back(a.q);}z.coalesced_pairing_terms=p.size();z.miller_loop_terms=p.size();GT out;if(p.empty()){out.setOne();if(s)*s=z;return out;}GT miller;mcl::bn::millerLoopVec(miller,p.data(),q.data(),p.size(),true);++z.miller_loop_batches;mcl::bn::finalExp(out,miller);++z.final_exponentiations;if(s)*s=z;return out;}
GT evaluate_pairing_terms(const SymbolicGtExpression&e,const PairingAtomResolver&r,size_t*calls){PairingProductStats s;GT z=evaluate_pairing_terms_reference(e,r,&s);if(calls)*calls+=s.ordinary_pairing_calls;return z;}
GT evaluate_symbolic_expression(SymbolicGtExpression e,const GtAtomResolver&gt,const PairingAtomResolver&pair,MultiexpMode mode,size_t*calls,PairingProductStats*stats){using Clock=std::chrono::steady_clock;normalize(e);std::vector<GT>b;std::vector<Fr>x;b.reserve(e.gt_terms.size());x.reserve(e.gt_terms.size());for(auto&[id,c]:e.gt_terms){b.push_back(gt(id));x.push_back(c);}auto t0=Clock::now();GT a=mode==MultiexpMode::Pippenger?gt_multiexp_pippenger(b,x):gt_multiexp_reference(b,x);auto t1=Clock::now();PairingProductStats ps;GT p=mode==MultiexpMode::Pippenger?evaluate_pairing_terms_multi(e,pair,&ps):evaluate_pairing_terms_reference(e,pair,&ps);auto t2=Clock::now();ps.gt_msm_ms=std::chrono::duration<double,std::milli>(t1-t0).count();ps.multi_pairing_ms=std::chrono::duration<double,std::milli>(t2-t1).count();if(calls)*calls+=mode==MultiexpMode::Pippenger?ps.miller_loop_batches:ps.ordinary_pairing_calls;if(stats)*stats=ps;GT z;GT::mul(z,a,p);return z;}
}
